// scripts/dictquotes.js

// Array of Business Dictionary Terms and Definitions
const businessDictionary = [
    {
        term: "Incubator",
        definition: "An organization or place designed to accelerate the growth and success of startup companies through various support resources and services."
    },
    {
        term: "Due Diligence",
        definition: "The research and analysis of a company or organization conducted in preparation for a business transaction, such as a merger, acquisition, or investment."
    },
    {
        term: "Angel Investor",
        definition: "An affluent individual who provides capital for a business start-up, usually in exchange for convertible debt or ownership equity."
    },
    {
        term: "Venture Capital",
        definition: "A form of private equity and a type of financing that investors provide to startup companies and small businesses that have been deemed to have high growth potential."
    },
    {
        term: "Burn Rate",
        definition: "The rate at which an enterprise (typically a startup) spends money, especially venture capital, in excess of income."
    },
    {
        term: "Leverage",
        definition: "Using borrowed capital for an investment, expecting the profits made to be greater than the interest payable."
    },
    {
        term: "Monopoly",
        definition: "Exclusive possession or control of the supply of or trade in a commodity or service."
    },
    {
        term: "Diversification",
        definition: "A strategy of increasing sales by introducing new products into new markets."
    },
    {
        term: "Scalability",
        definition: "The ability of a system to handle a growing amount of work by adding resources to the system."
    },
    {
        term: "ROI (Return on Investment)",
        definition: "A performance measure used to evaluate the efficiency of an investment or compare the efficiency of a number of different investments."
    },
    {
        term: "SWOT Analysis",
        definition: "A strategic planning technique used to help an organization identify Strengths, Weaknesses, Opportunities, and Threats related to business competition or project planning."
    },
    {
        term: "Niche Market",
        definition: "A subset of the market on which a specific product is focused. The niche market defines the specific product features aimed at satisfying specific market needs."
    },
    {
        term: "Disruption",
        definition: "An innovation that creates a new market and value network and eventually disrupts an existing market and value network, displacing established market-leading firms, products, and alliances."
    },
    {
        term: "Liquidity",
        definition: "The ease with which an asset, or security, can be converted into ready cash without affecting its market price."
    },
    {
        term: "Gross Margin",
        definition: "The difference between revenue and cost of goods sold (COGS) divided by revenue, expressed as a percentage."
    },
    {
        term: "Net Profit",
        definition: "The actual profit after working expenses not included in the calculation of gross profit have been paid."
    },
    {
        term: "Supply Chain",
        definition: "The sequence of processes involved in the production and distribution of a commodity."
    },
    {
        term: "Value Proposition",
        definition: "A promise of value to be delivered. It's the primary reason a prospect should buy from you."
    },
    {
        term: "Bootstrapping",
        definition: "Building a company from scratch with very little money, relying on personal savings and early sales rather than external investors."
    },
    {
        term: "Market Share",
        definition: "The percentage of total sales in an industry generated by a particular company."
    },
    {
        term: "B2B (Business-to-Business)",
        definition: "Refers to a business model where a company sells its products or services directly to other businesses."
    },
    {
        term: "B2C (Business-to-Consumer)",
        definition: "Refers to a business model where a company sells its products or services directly to individual consumers."
    },
    {
        term: "ROI (Return on Investment)",
        definition: "A performance measure used to evaluate the efficiency of an investment or compare the efficiency of a number of different investments."
    }
];

// Array of Business Quotes with Authors
const businessQuotes = [
    {
        quote: "The only way to do great work is to love what you do.",
        author: "Steve Jobs"
    },
    {
        quote: "Your most unhappy customers are your greatest source of learning.",
        author: "Bill Gates"
    },
    {
        quote: "Success is not final; failure is not fatal: It is the courage to continue that counts.",
        author: "Winston S. Churchill"
    },
    {
        quote: "The best way to predict the future is to create it.",
        author: "Peter Drucker"
    },
    {
        quote: "If you are not willing to risk the usual, you will have to settle for the ordinary.",
        author: "Jim Rohn"
    },
    {
        quote: "Strive not to be a success, but rather to be of value.",
        author: "Albert Einstein"
    },
    {
        quote: "Innovation distinguishes between a leader and a follower.",
        author: "Steve Jobs"
    },
    {
        quote: "The customer's perception is your reality.",
        author: "Kate Zabriskie"
    },
    {
        quote: "Logic will get you from A to B. Imagination will take you everywhere.",
        author: "Albert Einstein"
    },
    {
        quote: "Don't be afraid to give up the good to go for the great.",
        author: "John D. Rockefeller"
    },
    {
        quote: "I have not failed. I've just found 10,000 ways that won't work.",
        author: "Thomas A. Edison"
    },
    {
        quote: "The greatest danger in times of turbulence is not the turbulence; it is to act with yesterday's logic.",
        author: "Peter Drucker"
    },
    {
        quote: "The price of success is hard work, dedication to the job at hand, and the determination that whether we win or lose, we have applied the best of ourselves to the task at hand.",
        author: "Vince Lombardi"
    },
    {
        quote: "Quality is not an act, it is a habit.",
        author: "Aristotle"
    },
    {
        quote: "The function of leadership is to produce more leaders, not more followers.",
        author: "Ralph Nader"
    },
    {
        quote: "You miss 100% of the shots you don't take.",
        author: "Wayne Gretzky"
    },
    {
        quote: "If you want to build a ship, don't drum up people to collect wood and don't assign them tasks and work, but rather teach them to long for the endless immensity of the sea.",
        author: "Antoine de Saint-Exupéry"
    },
    {
        quote: "The critical ingredient is getting off your butt and doing something. It's as simple as that. A lot of people have ideas, but there are few who decide to do something about them now. Not tomorrow. Not next week. But today. The true entrepreneur is a doer, not a dreamer.",
        author: "Nolan Bushnell"
    }
];
