// products.js
// --- Data Definitions ---
const ALL_PRODUCTS = [
    {
        id: 'prod149',
        name: 'Classic Mattel Game',
        description: 'Discover the Classic Mattel Game, a Toys & Games essential from Mattel. This product boasts 2 unique features and a sleek design. Perfect for toys & games enthusiasts.',
        category: 'Toys & Games',
        subCategory: 'Board Games',
        brand: 'Mattel',
        price: 2000.00,
        originalPrice: null,
        isDiscounted: false,
        images: ['images/products/classic-mattel-game.webp', 'images/products/image2.webp', 'images/products/image3.webp'],
        rating: 4.1,
        reviewsCount: 110,
        inStock: 280,
        sku: 'MAT-TOY-PROD149',
        features: ['Multi-functional', 'Durable Construction'],
        shipping: 'local',
        waitingPeriod: '2-3 business days',
        minOrderQuantity: 1,
        maxOrderQuantity: 20,
        availableColors: ['Multi-color'],
        color: 'Multi-color',
        storage: null,
        size: null
    },
    {
        id: 'prod150',
        name: 'Ergonomic Office Chair',
        description: 'Boost your productivity with this ergonomic office chair. Designed for comfort and support during long working hours.',
        category: 'Office & Stationery',
        subCategory: 'Office Furniture',
        brand: 'Logitech', // Example brand
        price: 350.00,
        originalPrice: 400.00,
        isDiscounted: true,
        images: ['https://placehold.co/300x200/F0F0F0/333333?text=Office+Chair'],
        rating: 4.5,
        reviewsCount: 250,
        inStock: 150,
        sku: 'LOG-OFF-CHAIR-150',
        features: ['Adjustable Height', 'Lumbar Support'],
        shipping: 'local',
        waitingPeriod: '3-5 business days',
        minOrderQuantity: 1,
        maxOrderQuantity: 5,
        availableColors: ['Black', 'Grey'],
        color: 'Black',
        storage: null,
        size: null
    },
    {
        id: 'prod151',
        name: 'High-Performance Laptop',
        description: 'Experience blazing fast performance with this high-end laptop, perfect for gaming and professional work.',
        category: 'Electronics',
        subCategory: 'Laptops',
        brand: 'HP',
        price: 1200.00,
        originalPrice: null,
        isDiscounted: false,
        images: ['https://placehold.co/300x200/D0D0D0/333333?text=Laptop'],
        rating: 4.8,
        reviewsCount: 500,
        inStock: 80,
        sku: 'HP-LAP-PRO151',
        features: ['16GB RAM', '1TB SSD', 'RTX 3060'],
        shipping: 'local',
        waitingPeriod: '1-2 business days',
        minOrderQuantity: 1,
        maxOrderQuantity: 3,
        availableColors: ['Silver'],
        color: 'Silver',
        storage: '1TB',
        size: '15.6 inch'
    },
    {
        id: 'prod152',
        name: 'Wireless Bluetooth Speaker',
        description: 'Portable and powerful wireless speaker with deep bass and clear highs. Perfect for parties or personal use.',
        category: 'Electronics',
        subCategory: 'Audio',
        brand: 'Sony',
        price: 99.99,
        originalPrice: 120.00,
        isDiscounted: true,
        images: ['https://placehold.co/300x200/C0C0C0/333333?text=Speaker'],
        rating: 4.3,
        reviewsCount: 180,
        inStock: 300,
        sku: 'SONY-AUD-SPK152',
        features: ['Waterproof', '20-hour Battery Life'],
        shipping: 'local',
        waitingPeriod: '2-3 business days',
        minOrderQuantity: 1,
        maxOrderQuantity: 10,
        availableColors: ['Black', 'Blue', 'Red'],
        color: 'Black',
        storage: null,
        size: null
    },
    {
        id: 'prod153',
        name: 'Smartwatch with Heart Rate Monitor',
        description: 'Stay fit and connected with this stylish smartwatch. Tracks your activity, heart rate, and notifications.',
        category: 'Electronics',
        subCategory: 'Wearables',
        brand: 'Samsung',
        price: 180.00,
        originalPrice: null,
        isDiscounted: false,
        images: ['https://placehold.co/300x200/B0B0B0/333333?text=Smartwatch'],
        rating: 4.6,
        reviewsCount: 320,
        inStock: 120,
        sku: 'SAM-WEAR-SMW153',
        features: ['GPS', 'Water Resistant'],
        shipping: 'local',
        waitingPeriod: '1-2 business days',
        minOrderQuantity: 1,
        maxOrderQuantity: 5,
        availableColors: ['Black', 'Rose Gold'],
        color: 'Black',
        storage: null,
        size: null
    },
    {
        id: 'prod154',
        name: 'Digital SLR Camera',
        description: 'Capture stunning photos and videos with this professional-grade DSLR camera. Perfect for enthusiasts and pros.',
        category: 'Electronics',
        subCategory: 'Cameras',
        brand: 'Canon',
        price: 750.00,
        originalPrice: 850.00,
        isDiscounted: true,
        images: ['https://placehold.co/300x200/A0A0A0/333333?text=DSLR+Camera'],
        rating: 4.7,
        reviewsCount: 400,
        inStock: 70,
        sku: 'CAN-CAM-DSLR154',
        features: ['24MP Sensor', '4K Video'],
        shipping: 'local',
        waitingPeriod: '2-3 business days',
        minOrderQuantity: 1,
        maxOrderQuantity: 2,
        availableColors: ['Black'],
        color: 'Black',
        storage: null,
        size: null
    },
    {
        id: 'prod155',
        name: 'Men\'s Casual T-Shirt',
        description: 'Comfortable and stylish casual t-shirt for men. Made from breathable cotton.',
        category: 'Fashion & Apparel',
        subCategory: "Men's Clothing",
        brand: 'H&M',
        price: 15.00,
        originalPrice: null,
        isDiscounted: false,
        images: ['https://placehold.co/300x200/909090/333333?text=Mens+T-Shirt'],
        rating: 4.0,
        reviewsCount: 90,
        inStock: 500,
        sku: 'HM-MEN-TSHIRT155',
        features: ['Soft Fabric', 'Regular Fit'],
        shipping: 'local',
        waitingPeriod: '3-5 business days',
        minOrderQuantity: 1,
        maxOrderQuantity: 50,
        availableColors: ['White', 'Black', 'Blue'],
        color: 'White',
        storage: null,
        size: 'M'
    },
    {
        id: 'prod156',
        name: 'Women\'s Summer Dress',
        description: 'Light and airy summer dress, perfect for a casual day out or a beach vacation.',
        category: 'Fashion & Apparel',
        subCategory: "Women's Clothing",
        brand: 'Zara',
        price: 45.00,
        originalPrice: 60.00,
        isDiscounted: true,
        images: ['https://placehold.co/300x200/808080/333333?text=Womens+Dress'],
        rating: 4.2,
        reviewsCount: 150,
        inStock: 200,
        sku: 'ZAR-WOM-DRESS156',
        features: ['Breathable', 'Floral Print'],
        shipping: 'local',
        waitingPeriod: '3-5 business days',
        minOrderQuantity: 1,
        maxOrderQuantity: 10,
        availableColors: ['Floral', 'Red'],
        color: 'Floral',
        storage: null,
        size: 'S'
    },
    {
        id: 'prod157',
        name: 'Kids\' Play Tent',
        description: 'A fun and colorful play tent for kids, perfect for indoor and outdoor adventures.',
        category: 'Baby & Kids',
        subCategory: "Kid's Toys", // Changed from Apparel as per product type
        brand: 'Fisher-Price',
        price: 70.00,
        originalPrice: null,
        isDiscounted: false,
        images: ['https://placehold.co/300x200/707070/333333?text=Kids+Tent'],
        rating: 4.4,
        reviewsCount: 80,
        inStock: 100,
        sku: 'FPR-KID-TENT157',
        features: ['Easy Setup', 'Durable Fabric'],
        shipping: 'local',
        waitingPeriod: '2-3 business days',
        minOrderQuantity: 1,
        maxOrderQuantity: 5,
        availableColors: ['Multi-color'],
        color: 'Multi-color',
        storage: null,
        size: null
    },
    {
        id: 'prod158',
        name: 'Running Shoes',
        description: 'Lightweight and supportive running shoes for optimal performance and comfort.',
        category: 'Fashion & Apparel',
        subCategory: 'Shoes',
        brand: 'Nike',
        price: 90.00,
        originalPrice: 110.00,
        isDiscounted: true,
        images: ['https://placehold.co/300x200/606060/333333?text=Running+Shoes'],
        rating: 4.7,
        reviewsCount: 300,
        inStock: 250,
        sku: 'NIK-RUN-SHOE158',
        features: ['Breathable Mesh', 'Cushioned Sole'],
        shipping: 'local',
        waitingPeriod: '1-2 business days',
        minOrderQuantity: 1,
        maxOrderQuantity: 5,
        availableColors: ['Black', 'White', 'Red'],
        color: 'Black',
        storage: null,
        size: 'US 10'
    },
    {
        id: 'prod159',
        name: 'Leather Handbag',
        description: 'Elegant genuine leather handbag, perfect for daily use or special occasions. Spacious and stylish.',
        category: 'Fashion & Apparel',
        subCategory: 'Accessories',
        brand: 'Zara', // Example brand
        price: 120.00,
        originalPrice: null,
        isDiscounted: false,
        images: ['https://placehold.co/300x200/505050/333333?text=Handbag'],
        rating: 4.5,
        reviewsCount: 100,
        inStock: 80,
        sku: 'ZAR-ACC-HANDBAG159',
        features: ['Genuine Leather', 'Multiple Compartments'],
        shipping: 'local',
        waitingPeriod: '2-3 business days',
        minOrderQuantity: 1,
        maxOrderQuantity: 3,
        availableColors: ['Brown', 'Black'],
        color: 'Brown',
        storage: null,
        size: null
    },
    {
        id: 'prod160',
        name: 'Non-Stick Cookware Set',
        description: 'Complete non-stick cookware set for all your cooking needs. Durable and easy to clean.',
        category: 'Home & Kitchen',
        subCategory: 'Cookware',
        brand: 'Tefal',
        price: 150.00,
        originalPrice: 180.00,
        isDiscounted: true,
        images: ['https://placehold.co/300x200/404040/333333?text=Cookware'],
        rating: 4.6,
        reviewsCount: 200,
        inStock: 110,
        sku: 'TEF-HOM-COOK160',
        features: ['Dishwasher Safe', 'Even Heat Distribution'],
        shipping: 'local',
        waitingPeriod: '3-5 business days',
        minOrderQuantity: 1,
        maxOrderQuantity: 2,
        availableColors: ['Black'],
        color: 'Black',
        storage: null,
        size: null
    },
    {
        id: 'prod161',
        name: 'Smart Home Lighting Kit',
        description: 'Control your home lighting from your smartphone with this easy-to-install smart lighting kit.',
        category: 'Home & Kitchen',
        subCategory: 'Decor', // Assuming decor for smart home integration
        brand: 'Philips',
        price: 80.00,
        originalPrice: null,
        isDiscounted: false,
        images: ['https://placehold.co/300x200/303030/333333?text=Smart+Light'],
        rating: 4.3,
        reviewsCount: 120,
        inStock: 90,
        sku: 'PHI-HOM-LIGHT161',
        features: ['Voice Control', 'Dimmable'],
        shipping: 'local',
        waitingPeriod: '2-3 business days',
        minOrderQuantity: 1,
        maxOrderQuantity: 5,
        availableColors: ['White'],
        color: 'White',
        storage: null,
        size: null
    },
    {
        id: 'prod162',
        name: 'Luxury Bedding Set',
        description: 'Indulge in ultimate comfort with this soft and luxurious bedding set. Made from premium materials.',
        category: 'Home & Kitchen',
        subCategory: 'Bedding',
        brand: 'Dyson', // Example brand, though Dyson is usually appliances
        price: 250.00,
        originalPrice: null,
        isDiscounted: false,
        images: ['https://placehold.co/300x200/202020/333333?text=Bedding'],
        rating: 4.8,
        reviewsCount: 60,
        inStock: 40,
        sku: 'DYS-HOM-BED162',
        features: ['Hypoallergenic', 'Machine Washable'],
        shipping: 'local',
        waitingPeriod: '3-5 business days',
        minOrderQuantity: 1,
        maxOrderQuantity: 2,
        availableColors: ['White', 'Grey', 'Navy'],
        color: 'White',
        storage: null,
        size: 'King'
    },
    {
        id: 'prod163',
        name: 'Organic Skincare Set',
        description: 'Nourish your skin with this organic skincare set. Gentle formulas for all skin types.',
        category: 'Beauty & Personal Care',
        subCategory: 'Skincare',
        brand: 'Nivea',
        price: 60.00,
        originalPrice: null,
        isDiscounted: false,
        images: ['https://placehold.co/300x200/101010/333333?text=Skincare'],
        rating: 4.5,
        reviewsCount: 180,
        inStock: 150,
        sku: 'NIV-BEA-SKIN163',
        features: ['Natural Ingredients', 'Dermatologist Tested'],
        shipping: 'local',
        waitingPeriod: '2-3 business days',
        minOrderQuantity: 1,
        maxOrderQuantity: 10,
        availableColors: ['N/A'],
        color: 'N/A',
        storage: null,
        size: null
    },
    {
        id: 'prod164',
        name: 'Professional Hair Dryer',
        description: 'Achieve salon-quality blowouts at home with this powerful and lightweight hair dryer.',
        category: 'Beauty & Personal Care',
        subCategory: 'Haircare',
        brand: 'Dyson',
        price: 399.00,
        originalPrice: null,
        isDiscounted: false,
        images: ['https://placehold.co/300x200/000000/FFFFFF?text=Hair+Dryer'],
        rating: 4.9,
        reviewsCount: 250,
        inStock: 60,
        sku: 'DYS-BEA-HAIR164',
        features: ['Fast Drying', 'Heat Control'],
        shipping: 'local',
        waitingPeriod: '1-2 business days',
        minOrderQuantity: 1,
        maxOrderQuantity: 2,
        availableColors: ['Pink', 'Silver'],
        color: 'Pink',
        storage: null,
        size: null
    },
    {
        id: 'prod165',
        name: 'Waterproof Mascara',
        description: 'Long-lasting waterproof mascara for voluminous lashes that stay put all day.',
        category: 'Beauty & Personal Care',
        subCategory: 'Makeup',
        brand: 'L\'Oreal',
        price: 18.00,
        originalPrice: null,
        isDiscounted: false,
        images: ['https://placehold.co/300x200/555555/FFFFFF?text=Mascara'],
        rating: 4.0,
        reviewsCount: 90,
        inStock: 300,
        sku: 'LOR-BEA-MASC165',
        features: ['Smudge-proof', 'Volumizing'],
        shipping: 'local',
        waitingPeriod: '2-3 business days',
        minOrderQuantity: 1,
        maxOrderQuantity: 20,
        availableColors: ['Black'],
        color: 'Black',
        storage: null,
        size: null
    },
    {
        id: 'prod166',
        name: 'Unisex Eau de Parfum',
        description: 'A captivating unisex fragrance with notes of citrus, wood, and musk. Long-lasting and versatile.',
        category: 'Beauty & Personal Care',
        subCategory: 'Fragrances',
        brand: 'Garnier', // Example brand
        price: 75.00,
        originalPrice: null,
        isDiscounted: false,
        images: ['https://placehold.co/300x200/666666/FFFFFF?text=Perfume'],
        rating: 4.6,
        reviewsCount: 110,
        inStock: 70,
        sku: 'GAR-BEA-FRAG166',
        features: ['Long-lasting', 'Unique Scent'],
        shipping: 'local',
        waitingPeriod: '2-3 business days',
        minOrderQuantity: 1,
        maxOrderQuantity: 5,
        availableColors: ['N/A'],
        color: 'N/A',
        storage: null,
        size: '100ml'
    },
    {
        id: 'prod167',
        name: 'Beard Trimmer Kit',
        description: 'All-in-one beard trimmer kit for precise grooming. Includes multiple attachments.',
        category: 'Beauty & Personal Care',
        subCategory: 'Grooming',
        brand: 'Philips',
        price: 50.00,
        originalPrice: null,
        isDiscounted: false,
        images: ['https://placehold.co/300x200/777777/FFFFFF?text=Trimmer'],
        rating: 4.3,
        reviewsCount: 130,
        inStock: 180,
        sku: 'PHI-BEA-GROOM167',
        features: ['Cordless', 'Waterproof'],
        shipping: 'local',
        waitingPeriod: '2-3 business days',
        minOrderQuantity: 1,
        maxOrderQuantity: 10,
        availableColors: ['Black'],
        color: 'Black',
        storage: null,
        size: null
    },
    {
        id: 'prod168',
        name: 'Home Gym Multi-Station',
        description: 'Build strength and muscle with this versatile home gym multi-station. Perfect for full-body workouts.',
        category: 'Sports & Outdoors',
        subCategory: 'Fitness',
        brand: 'Adidas', // Example brand
        price: 450.00,
        originalPrice: 550.00,
        isDiscounted: true,
        images: ['https://placehold.co/300x200/888888/FFFFFF?text=Home+Gym'],
        rating: 4.7,
        reviewsCount: 70,
        inStock: 30,
        sku: 'ADI-SPO-GYM168',
        features: ['Multiple Exercises', 'Durable Construction'],
        shipping: 'local',
        waitingPeriod: '5-7 business days',
        minOrderQuantity: 1,
        maxOrderQuantity: 1,
        availableColors: ['Black'],
        color: 'Black',
        storage: null,
        size: null
    },
    {
        id: 'prod169',
        name: 'Camping Tent 4-Person',
        description: 'Spacious and easy-to-setup camping tent for up to 4 people. Ideal for family camping trips.',
        category: 'Sports & Outdoors',
        subCategory: 'Camping',
        brand: 'GoPro', // Example brand
        price: 180.00,
        originalPrice: null,
        isDiscounted: false,
        images: ['https://placehold.co/300x200/999999/FFFFFF?text=Camping+Tent'],
        rating: 4.4,
        reviewsCount: 90,
        inStock: 100,
        sku: 'GOP-SPO-TENT169',
        features: ['Waterproof', 'Ventilated'],
        shipping: 'local',
        waitingPeriod: '3-5 business days',
        minOrderQuantity: 1,
        maxOrderQuantity: 3,
        availableColors: ['Green', 'Blue'],
        color: 'Green',
        storage: null,
        size: null
    },
    {
        id: 'prod170',
        name: 'Mountain Bike 29er',
        description: 'Conquer any trail with this rugged 29-inch mountain bike. Features durable frame and responsive suspension.',
        category: 'Sports & Outdoors',
        subCategory: 'Cycling',
        brand: 'Garmin', // Example brand
        price: 600.00,
        originalPrice: 700.00,
        isDiscounted: true,
        images: ['https://placehold.co/300x200/AAAAAA/FFFFFF?text=Mountain+Bike'],
        rating: 4.6,
        reviewsCount: 110,
        inStock: 40,
        sku: 'GAR-SPO-BIKE170',
        features: ['Aluminum Frame', 'Disc Brakes'],
        shipping: 'local',
        waitingPeriod: '5-7 business days',
        minOrderQuantity: 1,
        maxOrderQuantity: 1,
        availableColors: ['Black', 'Red'],
        color: 'Black',
        storage: null,
        size: '29 inch'
    },
    {
        id: 'prod171',
        name: 'Basketball Hoop Portable',
        description: 'Enjoy basketball anywhere with this portable hoop. Adjustable height for all ages.',
        category: 'Sports & Outdoors',
        subCategory: 'Team Sports',
        brand: 'Puma', // Example brand
        price: 220.00,
        originalPrice: null,
        isDiscounted: false,
        images: ['https://placehold.co/300x200/BBBBBB/FFFFFF?text=Basketball+Hoop'],
        rating: 4.2,
        reviewsCount: 50,
        inStock: 60,
        sku: 'PUM-SPO-HOOP171',
        features: ['Adjustable Height', 'Wheels for Portability'],
        shipping: 'local',
        waitingPeriod: '3-5 business days',
        minOrderQuantity: 1,
        maxOrderQuantity: 2,
        availableColors: ['Black'],
        color: 'Black',
        storage: null,
        size: null
    },
    {
        id: 'prod172',
        name: 'Hiking Backpack 60L',
        description: 'Large capacity hiking backpack, perfect for multi-day treks. Comfortable and durable.',
        category: 'Sports & Outdoors',
        subCategory: 'Outdoor Gear',
        brand: 'North Face', // Example brand
        price: 130.00,
        originalPrice: null,
        isDiscounted: false,
        images: ['https://placehold.co/300x200/CCCCCC/FFFFFF?text=Hiking+Pack'],
        rating: 4.5,
        reviewsCount: 80,
        inStock: 90,
        sku: 'TNF-SPO-BPK172',
        features: ['Water Resistant', 'Multiple Pockets'],
        shipping: 'local',
        waitingPeriod: '2-3 business days',
        minOrderQuantity: 1,
        maxOrderQuantity: 5,
        availableColors: ['Green', 'Blue'],
        color: 'Green',
        storage: null,
        size: '60L'
    },
    {
        id: 'prod173',
        name: 'Bestselling Novel',
        description: 'A gripping tale of mystery and adventure that will keep you on the edge of your seat.',
        category: 'Books, Movies & Music',
        subCategory: 'Books',
        brand: 'Penguin Random House', // Example brand
        price: 20.00,
        originalPrice: null,
        isDiscounted: false,
        images: ['https://placehold.co/300x200/DDDDDD/333333?text=Book'],
        rating: 4.1,
        reviewsCount: 200,
        inStock: 400,
        sku: 'PRH-BMM-BOOK173',
        features: ['Paperback', 'Fiction'],
        shipping: 'local',
        waitingPeriod: '2-3 business days',
        minOrderQuantity: 1,
        maxOrderQuantity: 10,
        availableColors: ['N/A'],
        color: 'N/A',
        storage: null,
        size: null
    },
    {
        id: 'prod174',
        name: '4K Ultra HD Blu-ray Player',
        description: 'Experience stunning visuals and immersive audio with this 4K Blu-ray player.',
        category: 'Books, Movies & Music',
        subCategory: 'Movies',
        brand: 'Sony',
        price: 250.00,
        originalPrice: null,
        isDiscounted: false,
        images: ['https://placehold.co/300x200/EEEEEE/333333?text=Blu-ray+Player'],
        rating: 4.5,
        reviewsCount: 70,
        inStock: 50,
        sku: 'SONY-BMM-BLURAY174',
        features: ['HDR Support', 'Dolby Atmos'],
        shipping: 'local',
        waitingPeriod: '2-3 business days',
        minOrderQuantity: 1,
        maxOrderQuantity: 2,
        availableColors: ['Black'],
        color: 'Black',
        storage: null,
        size: null
    },
    {
        id: 'prod175',
        name: 'Vinyl Record Player',
        description: 'Rediscover your favorite music with this retro-style vinyl record player. Built-in speakers.',
        category: 'Books, Movies & Music',
        subCategory: 'Music',
        brand: 'Audio-Technica', // Example brand
        price: 150.00,
        originalPrice: null,
        isDiscounted: false,
        images: ['https://placehold.co/300x200/FFFFFF/333333?text=Vinyl+Player'],
        rating: 4.2,
        reviewsCount: 60,
        inStock: 80,
        sku: 'AUD-BMM-VINYL175',
        features: ['Bluetooth Connectivity', '3-Speed'],
        shipping: 'local',
        waitingPeriod: '2-3 business days',
        minOrderQuantity: 1,
        maxOrderQuantity: 5,
        availableColors: ['Brown', 'Black'],
        color: 'Brown',
        storage: null,
        size: null
    },
    {
        id: 'prod176',
        name: 'Latest Gaming Console',
        description: 'Dive into next-gen gaming with the latest console. Stunning graphics and immersive gameplay.',
        category: 'Books, Movies & Music',
        subCategory: 'Video Games',
        brand: 'Nintendo',
        price: 499.00,
        originalPrice: null,
        isDiscounted: false,
        images: ['https://placehold.co/300x200/F0F0F0/333333?text=Gaming+Console'],
        rating: 4.9,
        reviewsCount: 600,
        inStock: 50,
        sku: 'NIN-BMM-CON176',
        features: ['4K Gaming', 'Fast Loading'],
        shipping: 'local',
        waitingPeriod: '1-2 business days',
        minOrderQuantity: 1,
        maxOrderQuantity: 1,
        availableColors: ['Black'],
        color: 'Black',
        storage: '1TB',
        size: null
    },
    {
        id: 'prod177',
        name: 'Educational Building Blocks',
        description: 'Inspire creativity and learning with these colorful educational building blocks for toddlers.',
        category: 'Toys & Games',
        subCategory: "Kid's Toys",
        brand: 'Lego',
        price: 30.00,
        originalPrice: null,
        isDiscounted: false,
        images: ['https://placehold.co/300x200/D0D0D0/333333?text=Building+Blocks'],
        rating: 4.5,
        reviewsCount: 150,
        inStock: 250,
        sku: 'LEG-TOY-BLOCK177',
        features: ['Non-toxic', 'Easy to Assemble'],
        shipping: 'local',
        waitingPeriod: '2-3 business days',
        minOrderQuantity: 1,
        maxOrderQuantity: 10,
        availableColors: ['Multi-color'],
        color: 'Multi-color',
        storage: null,
        size: null
    },
    {
        id: 'prod178',
        name: 'Strategy Board Game',
        description: 'Engage in epic battles of strategy and wit with this complex and rewarding board game.',
        category: 'Toys & Games',
        subCategory: 'Board Games',
        brand: 'Mattel',
        price: 40.00,
        originalPrice: null,
        isDiscounted: false,
        images: ['https://placehold.co/300x200/C0C0C0/333333?text=Strategy+Game'],
        rating: 4.6,
        reviewsCount: 100,
        inStock: 120,
        sku: 'MAT-TOY-STRAT178',
        features: ['2-4 Players', 'Ages 10+'],
        shipping: 'local',
        waitingPeriod: '2-3 business days',
        minOrderQuantity: 1,
        maxOrderQuantity: 5,
        availableColors: ['N/A'],
        color: 'N/A',
        storage: null,
        size: null
    },
    {
        id: 'prod179',
        name: 'Jigsaw Puzzle 1000 Pieces',
        description: 'Challenge your mind with this beautiful 1000-piece jigsaw puzzle featuring a scenic landscape.',
        category: 'Toys & Games',
        subCategory: 'Puzzles',
        brand: '3M', // Example brand
        price: 25.00,
        originalPrice: null,
        isDiscounted: false,
        images: ['https://placehold.co/300x200/B0B0B0/333333?text=Jigsaw+Puzzle'],
        rating: 4.0,
        reviewsCount: 70,
        inStock: 150,
        sku: '3M-TOY-PUZZLE179',
        features: ['High Quality Print', 'Challenging'],
        shipping: 'local',
        waitingPeriod: '2-3 business days',
        minOrderQuantity: 1,
        maxOrderQuantity: 10,
        availableColors: ['N/A'],
        color: 'N/A',
        storage: null,
        size: null
    },
    {
        id: 'prod180',
        name: 'Collectible Action Figure',
        description: 'Highly detailed collectible action figure from a popular movie franchise. Limited edition.',
        category: 'Toys & Games',
        subCategory: 'Action Figures',
        brand: 'Barbie', // Example brand
        price: 55.00,
        originalPrice: null,
        isDiscounted: false,
        images: ['https://placehold.co/300x200/A0A0A0/333333?text=Action+Figure'],
        rating: 4.7,
        reviewsCount: 40,
        inStock: 30,
        sku: 'BAR-TOY-FIG180',
        features: ['Articulated Joints', 'Collector\'s Item'],
        shipping: 'local',
        waitingPeriod: '2-3 business days',
        minOrderQuantity: 1,
        maxOrderQuantity: 2,
        availableColors: ['N/A'],
        color: 'N/A',
        storage: null,
        size: null
    },
    {
        id: 'prod181',
        name: 'Baby Stroller',
        description: 'Lightweight and compact baby stroller, perfect for city strolls and travel. Easy to fold.',
        category: 'Baby & Kids',
        subCategory: 'Baby Gear',
        brand: 'Medela', // Example brand
        price: 280.00,
        originalPrice: null,
        isDiscounted: false,
        images: ['https://placehold.co/300x200/909090/333333?text=Baby+Stroller'],
        rating: 4.4,
        reviewsCount: 80,
        inStock: 50,
        sku: 'MED-BAB-STR181',
        features: ['One-hand Fold', 'Large Canopy'],
        shipping: 'local',
        waitingPeriod: '3-5 business days',
        minOrderQuantity: 1,
        maxOrderQuantity: 1,
        availableColors: ['Grey', 'Blue'],
        color: 'Grey',
        storage: null,
        size: null
    },
    {
        id: 'prod182',
        name: 'Disposable Diapers Jumbo Pack',
        description: 'Ultra-absorbent disposable diapers for maximum protection and comfort for your baby.',
        category: 'Baby & Kids',
        subCategory: 'Diapers',
        brand: 'Pampers', // Example brand
        price: 35.00,
        originalPrice: null,
        isDiscounted: false,
        images: ['https://placehold.co/300x200/808080/333333?text=Diapers'],
        rating: 4.6,
        reviewsCount: 300,
        inStock: 500,
        sku: 'PAM-BAB-DIAP182',
        features: ['Wetness Indicator', 'Soft Liner'],
        shipping: 'local',
        waitingPeriod: '2-3 business days',
        minOrderQuantity: 1,
        maxOrderQuantity: 5,
        availableColors: ['N/A'],
        color: 'N/A',
        storage: null,
        size: 'Size 4'
    },
    {
        id: 'prod183',
        name: 'Baby Bottle Set',
        description: 'Complete baby bottle set with anti-colic design. BPA-free and easy to clean.',
        category: 'Baby & Kids',
        subCategory: 'Feeding',
        brand: 'Philips',
        price: 25.00,
        originalPrice: null,
        isDiscounted: false,
        images: ['https://placehold.co/300x200/707070/333333?text=Baby+Bottles'],
        rating: 4.3,
        reviewsCount: 180,
        inStock: 200,
        sku: 'PHI-BAB-BOTTLE183',
        features: ['Anti-colic', 'BPA-Free'],
        shipping: 'local',
        waitingPeriod: '2-3 business days',
        minOrderQuantity: 1,
        maxOrderQuantity: 10,
        availableColors: ['Clear'],
        color: 'Clear',
        storage: null,
        size: null
    },
    {
        id: 'prod184',
        name: 'Nursery Crib',
        description: 'Stylish and safe nursery crib for your baby. Adjustable mattress height.',
        category: 'Baby & Kids',
        subCategory: 'Nursery',
        brand: 'Fisher-Price',
        price: 180.00,
        originalPrice: null,
        isDiscounted: false,
        images: ['https://placehold.co/300x200/606060/333333?text=Baby+Crib'],
        rating: 4.5,
        reviewsCount: 60,
        inStock: 40,
        sku: 'FPR-BAB-CRIB184',
        features: ['Adjustable Height', 'Solid Wood'],
        shipping: 'local',
        waitingPeriod: '5-7 business days',
        minOrderQuantity: 1,
        maxOrderQuantity: 1,
        availableColors: ['White', 'Espresso'],
        color: 'White',
        storage: null,
        size: null
    },
    {
        id: 'prod185',
        name: 'Kids\' Study Desk',
        description: 'Ergonomic study desk for kids, perfect for homework and creative activities. Durable and easy to clean.',
        category: 'Baby & Kids',
        subCategory: 'Kids Furniture',
        brand: 'IKEA', // Example brand
        price: 90.00,
        originalPrice: null,
        isDiscounted: false,
        images: ['https://placehold.co/300x200/505050/333333?text=Kids+Desk'],
        rating: 4.2,
        reviewsCount: 70,
        inStock: 80,
        sku: 'IKE-BAB-DESK185',
        features: ['Adjustable Height', 'Storage Drawers'],
        shipping: 'local',
        waitingPeriod: '3-5 business days',
        minOrderQuantity: 1,
        maxOrderQuantity: 3,
        availableColors: ['White', 'Blue'],
        color: 'White',
        storage: null,
        size: null
    },
    {
        id: 'prod186',
        name: 'Car Stereo System',
        description: 'Upgrade your car audio with this powerful stereo system. Features Bluetooth and USB connectivity.',
        category: 'Automotive & Tools',
        subCategory: 'Car Parts',
        brand: 'Sony',
        price: 150.00,
        originalPrice: null,
        isDiscounted: false,
        images: ['https://placehold.co/300x200/404040/333333?text=Car+Stereo'],
        rating: 4.1,
        reviewsCount: 90,
        inStock: 100,
        sku: 'SONY-AUT-STEREO186',
        features: ['Bluetooth', 'USB Port'],
        shipping: 'local',
        waitingPeriod: '2-3 business days',
        minOrderQuantity: 1,
        maxOrderQuantity: 5,
        availableColors: ['Black'],
        color: 'Black',
        storage: null,
        size: null
    },
    {
        id: 'prod187',
        name: 'Car Phone Mount',
        description: 'Securely mount your smartphone in your car for navigation and hands-free calls. Universal fit.',
        category: 'Automotive & Tools',
        subCategory: 'Auto Accessories',
        brand: 'Logitech',
        price: 20.00,
        originalPrice: null,
        isDiscounted: false,
        images: ['https://placehold.co/300x200/303030/333333?text=Phone+Mount'],
        rating: 4.0,
        reviewsCount: 150,
        inStock: 300,
        sku: 'LOG-AUT-MOUNT187',
        features: ['360 Rotation', 'Strong Grip'],
        shipping: 'local',
        waitingPeriod: '2-3 business days',
        minOrderQuantity: 1,
        maxOrderQuantity: 20,
        availableColors: ['Black'],
        color: 'Black',
        storage: null,
        size: null
    },
    {
        id: 'prod188',
        name: 'Cordless Drill Set',
        description: 'Powerful cordless drill set for all your DIY projects. Includes multiple drill bits and battery.',
        category: 'Automotive & Tools',
        subCategory: 'Power Tools',
        brand: 'Bosch',
        price: 120.00,
        originalPrice: 150.00,
        isDiscounted: true,
        images: ['https://placehold.co/300x200/202020/333333?text=Cordless+Drill'],
        rating: 4.7,
        reviewsCount: 200,
        inStock: 90,
        sku: 'BOS-AUT-DRILL188',
        features: ['High Torque', 'Long Battery Life'],
        shipping: 'local',
        waitingPeriod: '2-3 business days',
        minOrderQuantity: 1,
        maxOrderQuantity: 5,
        availableColors: ['Blue'],
        color: 'Blue',
        storage: null,
        size: null
    },
    {
        id: 'prod189',
        name: 'Adjustable Wrench Set',
        description: 'Durable adjustable wrench set for various tasks. Essential for every toolbox.',
        category: 'Automotive & Tools',
        subCategory: 'Hand Tools',
        brand: 'Stanley',
        price: 40.00,
        originalPrice: null,
        isDiscounted: false,
        images: ['https://placehold.co/300x200/101010/333333?text=Wrench+Set'],
        rating: 4.3,
        reviewsCount: 110,
        inStock: 200,
        sku: 'STA-AUT-WRENCH189',
        features: ['Chrome Vanadium Steel', 'Comfort Grip'],
        shipping: 'local',
        waitingPeriod: '2-3 business days',
        minOrderQuantity: 1,
        maxOrderQuantity: 10,
        availableColors: ['Silver'],
        color: 'Silver',
        storage: null,
        size: null
    },
    {
        id: 'prod190',
        name: 'Multivitamin Supplements',
        description: 'Comprehensive multivitamin supplements to support overall health and well-being.',
        category: 'Health & Wellness',
        subCategory: 'Vitamins',
        brand: 'Purina', // Example brand
        price: 25.00,
        originalPrice: null,
        isDiscounted: false,
        images: ['https://placehold.co/300x200/000000/FFFFFF?text=Multivitamin'],
        rating: 4.5,
        reviewsCount: 150,
        inStock: 300,
        sku: 'PUR-HEA-VIT190',
        features: ['Essential Nutrients', 'Easy to Swallow'],
        shipping: 'local',
        waitingPeriod: '2-3 business days',
        minOrderQuantity: 1,
        maxOrderQuantity: 10,
        availableColors: ['N/A'],
        color: 'N/A',
        storage: null,
        size: null
    },
    {
        id: 'prod191',
        name: 'Blood Pressure Monitor',
        description: 'Accurate and easy-to-use digital blood pressure monitor for home use. Large display.',
        category: 'Health & Wellness',
        subCategory: 'Medical Devices',
        brand: 'Oral-B', // Example brand
        price: 60.00,
        originalPrice: null,
        isDiscounted: false,
        images: ['https://placehold.co/300x200/555555/FFFFFF?text=BP+Monitor'],
        rating: 4.4,
        reviewsCount: 90,
        inStock: 120,
        sku: 'ORB-HEA-BPM191',
        features: ['Irregular Heartbeat Detection', 'Memory Function'],
        shipping: 'local',
        waitingPeriod: '2-3 business days',
        minOrderQuantity: 1,
        maxOrderQuantity: 5,
        availableColors: ['White'],
        color: 'White',
        storage: null,
        size: null
    },
    {
        id: 'prod192',
        name: 'Smart Fitness Tracker',
        description: 'Track your daily activity, sleep, and workouts with this sleek smart fitness tracker.',
        category: 'Health & Wellness',
        subCategory: 'Fitness Trackers',
        brand: 'Garmin',
        price: 90.00,
        originalPrice: null,
        isDiscounted: false,
        images: ['https://placehold.co/300x200/666666/FFFFFF?text=Fitness+Tracker'],
        rating: 4.6,
        reviewsCount: 200,
        inStock: 100,
        sku: 'GAR-HEA-FIT192',
        features: ['Heart Rate', 'Sleep Tracking'],
        shipping: 'local',
        waitingPeriod: '2-3 business days',
        minOrderQuantity: 1,
        maxOrderQuantity: 5,
        availableColors: ['Black', 'Pink'],
        color: 'Black',
        storage: null,
        size: null
    },
    {
        id: 'prod193',
        name: 'Dog Food Premium Blend',
        description: 'Nutrient-rich premium dog food for adult dogs. Supports healthy digestion and coat.',
        category: 'Pet Supplies',
        subCategory: 'Dog Food',
        brand: 'Royal Canin',
        price: 50.00,
        originalPrice: null,
        isDiscounted: false,
        images: ['https://placehold.co/300x200/777777/FFFFFF?text=Dog+Food'],
        rating: 4.7,
        reviewsCount: 180,
        inStock: 250,
        sku: 'RCA-PET-DOGF193',
        features: ['High Protein', 'No Artificial Flavors'],
        shipping: 'local',
        waitingPeriod: '2-3 business days',
        minOrderQuantity: 1,
        maxOrderQuantity: 5,
        availableColors: ['N/A'],
        color: 'N/A',
        storage: null,
        size: '15kg'
    },
    {
        id: 'prod194',
        name: 'Cat Food Wet Variety Pack',
        description: 'Delicious wet cat food variety pack. Provides essential hydration and nutrients for cats.',
        category: 'Pet Supplies',
        subCategory: 'Cat Food',
        brand: 'Purina',
        price: 20.00,
        originalPrice: null,
        isDiscounted: false,
        images: ['https://placehold.co/300x200/888888/FFFFFF?text=Cat+Food'],
        rating: 4.5,
        reviewsCount: 120,
        inStock: 300,
        sku: 'PUR-PET-CATF194',
        features: ['Grain-Free', 'Rich in Protein'],
        shipping: 'local',
        waitingPeriod: '2-3 business days',
        minOrderQuantity: 1,
        maxOrderQuantity: 10,
        availableColors: ['N/A'],
        color: 'N/A',
        storage: null,
        size: '12-pack'
    },
    {
        id: 'prod195',
        name: 'Interactive Pet Toy',
        description: 'Keep your pet entertained for hours with this durable and interactive toy. Great for mental stimulation.',
        category: 'Pet Supplies',
        subCategory: 'Pet Toys',
        brand: 'Mattel', // Example brand
        price: 15.00,
        originalPrice: null,
        isDiscounted: false,
        images: ['https://placehold.co/300x200/999999/FFFFFF?text=Pet+Toy'],
        rating: 4.2,
        reviewsCount: 80,
        inStock: 200,
        sku: 'MAT-PET-TOY195',
        features: ['Durable', 'Treat Dispensing'],
        shipping: 'local',
        waitingPeriod: '2-3 business days',
        minOrderQuantity: 1,
        maxOrderQuantity: 15,
        availableColors: ['Multi-color'],
        color: 'Multi-color',
        storage: null,
        size: null
    },
    {
        id: 'prod196',
        name: 'Pet Grooming Brush',
        description: 'Gently remove loose fur and tangles with this effective pet grooming brush. Suitable for all coat types.',
        category: 'Pet Supplies',
        subCategory: 'Grooming',
        brand: 'Dyson', // Example brand
        price: 25.00,
        originalPrice: null,
        isDiscounted: false,
        images: ['https://placehold.co/300x200/AAAAAA/FFFFFF?text=Grooming+Brush'],
        rating: 4.0,
        reviewsCount: 70,
        inStock: 150,
        sku: 'DYS-PET-BRUSH196',
        features: ['Self-Cleaning', 'Comfort Grip'],
        shipping: 'local',
        waitingPeriod: '2-3 business days',
        minOrderQuantity: 1,
        maxOrderQuantity: 10,
        availableColors: ['N/A'],
        color: 'N/A',
        storage: null,
        size: null
    },
    {
        id: 'prod197',
        name: 'Pet Bed Orthopedic',
        description: 'Provide ultimate comfort for your pet with this orthopedic pet bed. Supports joints and promotes restful sleep.',
        category: 'Pet Supplies',
        subCategory: 'Beds',
        brand: 'Royal Canin', // Example brand
        price: 70.00,
        originalPrice: null,
        isDiscounted: false,
        images: ['https://placehold.co/300x200/BBBBBB/FFFFFF?text=Pet+Bed'],
        rating: 4.8,
        reviewsCount: 50,
        inStock: 80,
        sku: 'RCA-PET-BED197',
        features: ['Memory Foam', 'Removable Cover'],
        shipping: 'local',
        waitingPeriod: '3-5 business days',
        minOrderQuantity: 1,
        maxOrderQuantity: 3,
        availableColors: ['Grey', 'Brown'],
        color: 'Grey',
        storage: null,
        size: 'Large'
    },
    {
        id: 'prod198',
        name: 'Office Laser Printer',
        description: 'High-speed laser printer for efficient office use. Produces crisp, clear documents.',
        category: 'Office & Stationery',
        subCategory: 'Printers',
        brand: 'Brother',
        price: 200.00,
        originalPrice: null,
        isDiscounted: false,
        images: ['https://placehold.co/300x200/CCCCCC/FFFFFF?text=Laser+Printer'],
        rating: 4.3,
        reviewsCount: 100,
        inStock: 70,
        sku: 'BRO-OFF-PRINT198',
        features: ['Wireless Connectivity', 'Duplex Printing'],
        shipping: 'local',
        waitingPeriod: '2-3 business days',
        minOrderQuantity: 1,
        maxOrderQuantity: 5,
        availableColors: ['White'],
        color: 'White',
        storage: null,
        size: null
    },
    {
        id: 'prod199',
        name: 'Premium Notebooks 5-Pack',
        description: 'High-quality notebooks for all your writing needs. Smooth paper and durable covers.',
        category: 'Office & Stationery',
        subCategory: 'Stationery',
        brand: '3M', // Example brand
        price: 12.00,
        originalPrice: null,
        isDiscounted: false,
        images: ['https://placehold.co/300x200/DDDDDD/333333?text=Notebooks'],
        rating: 4.0,
        reviewsCount: 150,
        inStock: 400,
        sku: '3M-OFF-NOTE199',
        features: ['Lined Pages', 'A5 Size'],
        shipping: 'local',
        waitingPeriod: '2-3 business days',
        minOrderQuantity: 1,
        maxOrderQuantity: 20,
        availableColors: ['Multi-color'],
        color: 'Multi-color',
        storage: null,
        size: null
    },
    {
        id: 'prod200',
        name: 'Home Security Camera System',
        description: 'Monitor your home with this comprehensive security camera system. Remote viewing via app.',
        category: 'Security & Protection',
        subCategory: 'Home Security',
        brand: 'Xiaomi',
        price: 180.00,
        originalPrice: null,
        isDiscounted: false,
        images: ['https://placehold.co/300x200/EEEEEE/333333?text=Security+Camera'],
        rating: 4.5,
        reviewsCount: 100,
        inStock: 80,
        sku: 'XIA-SEC-CAM200',
        features: ['1080p HD', 'Night Vision'],
        shipping: 'local',
        waitingPeriod: '2-3 business days',
        minOrderQuantity: 1,
        maxOrderQuantity: 5,
        availableColors: ['White'],
        color: 'White',
        storage: null,
        size: null
    }
];

const TOP_BRANDS = [
    { id: 'brd-samsung', name: 'Samsung', logo: 'images/brandlogos/samsunglogo.webp', description: 'Global leader in electronics, known for innovative smartphones, TVs, and appliances.' },
    { id: 'brd-apple', name: 'Apple', logo: 'images/brandlogos/applelogo.webp', description: 'Pioneering technology company famous for iPhones, MacBooks, and intuitive software.' },
    { id: 'brd-sony', name: 'Sony', logo: 'images/brandlogos/sonylogo.webp', description: 'Japanese multinational conglomerate known for electronics, gaming, and entertainment.' },
    { id: 'brd-hp', name: 'HP', logo: 'images/brandlogos/hplogo.webp', description: 'Leading provider of personal computers, printers, and related solutions worldwide.' },
    { id: 'brd-dell', name: 'Dell', logo: 'images/brandlogos/delllogo.webp', description: 'American multinational computer technology company that develops, sells, repairs, and supports computers and related products and services.' },
    { id: 'brd-lg', name: 'LG', logo: 'images/brandlogos/lglogo.webp', description: 'South Korean multinational electronics company known for home appliances, electronics, and mobile communications.' },
    { id: 'brd-philips', name: 'Philips', logo: 'images/brandlogos/philipslogo.webp', description: 'Dutch multinational conglomerate corporation, known for electronics, healthcare, and lighting products.' },
    { id: 'brd-nike', name: 'Nike', logo: 'images/brandlogos/nikelogo.webp', description: 'American multinational corporation that is engaged in the design, development, manufacturing, and worldwide marketing and sales of footwear, apparel, equipment, accessories, and services.' },
    { id: 'brd-adidas', name: 'Adidas', logo: 'images/brandlogos/adidaslogo.webp', description: 'German multinational corporation, designing and manufacturing athletic and casual footwear, apparel, and accessories.' },
    { id: 'brd-puma', name: 'Puma', logo: 'images/brandlogos/pumalogo.webp', description: 'German multinational corporation that designs and manufactures athletic and casual footwear, apparel and accessories.' },
    { id: 'brd-dyson', name: 'Dyson', logo: 'images/brandlogos/dysonlogo.webp', description: 'British technology company known for innovative vacuum cleaners, air purifiers, and hair care products.' },
    { id: 'brd-bosch', name: 'Bosch', logo: 'images/brandlogos/boschlogo.webp', description: 'German multinational engineering and technology company, also a major manufacturer of home appliances.' },
    { id: 'brd-logitech', name: 'Logitech', logo: 'images/brandlogos/logitechlogo.webp', description: 'Swiss-American manufacturer of computer peripherals and software, specializing in input and interface devices.' },
    { id: 'brd-canon', name: 'Canon', logo: 'images/brandlogos/canonlogo.webp', description: 'Japanese multinational corporation specializing in optical, imaging, and industrial products, such as cameras, printers, and medical equipment.' },
    { id: 'brd-xiaomi', name: 'Xiaomi', logo: 'images/brandlogos/xiaomilogo.webp', description: 'Chinese multinational electronics company known for smartphones, smart hardware, and IoT platform products.' },
    { id: 'brd-hm', name: 'H&M', logo: 'images/brandlogos/hmlogo.webp', description: 'Swedish multinational retail-clothing company, known for its fast-fashion clothing for men, women, teenagers, and children.' },
    { id: 'brd-durex', name: 'Durex', logo: 'images/brandlogos/durexlogo.webp', description: 'British brand of condoms and personal lubricants owned by Reckitt Benckiser.' },
    { id: 'brd-barbie', name: 'Barbie', logo: 'images/brandlogos/barbielogo.webp', description: 'Fashion doll manufactured by American toy company Mattel, Inc.' },
    { id: 'brd-microsoft', name: 'Microsoft', logo: 'images/brandlogos/microsoftlogo.webp', description: 'American multinational technology corporation producing computer software, consumer electronics, personal computers, and related services.' },
    { id: 'brd-huawei', name: 'Huawei', logo: 'images/brandlogos/huaweilogo.webp', description: 'Chinese multinational technology company providing telecommunications equipment and selling consumer electronics, smartphones, and smart devices.' },
    { id: 'brd-zara', name: 'Zara', logo: 'images/brandlogos/zaralogo.webp', description: 'Spanish apparel retailer based in Arteixo, Galicia, Spain. The main brand of the Inditex group, the world\'s largest apparel retailer.' },
    { id: 'brd-royal-canin', name: 'Royal Canin', logo: 'images/brandlogos/royalcaninlogo.webp', description: 'French manufacturer of cat and dog food. A subsidiary of Mars, Incorporated.' },
    { id: 'brd-oral-b', name: 'Oral-B', logo: 'images/brandlogos/oralblogo.webp', description: 'American brand of oral hygiene products, including toothbrushes, toothpastes, mouthwashes, and dental floss.' },
    { id: 'brd-brother', name: 'Brother', logo: 'images/brandlogos/brotherlogo.webp', description: 'Japanese multinational electronics and electrical equipment company that produces a wide range of products including printers, multifunction printers, desktop computers, and other computer-related electronics.' },
    { id: 'brd-seiko', name: 'Seiko', logo: 'images/brandlogos/seikologo.webp', description: 'Japanese manufacturer of watches, clocks, electronic devices, semiconductors, and optical products.' },
    { id: 'brd-nintendo', name: 'Nintendo', logo: 'images/brandlogos/nintendologo.webp', description: 'Japanese multinational consumer electronics and video game company. One of the world\'s largest video game companies by market capitalization.' },
    { id: 'brd-fisher-price', name: 'Fisher-Price', logo: 'images/brandlogos/fisherpricelogo.webp', description: 'American company that manufactures toys for infants, toddlers, and preschool-aged children, headquartered in East Aurora, New York.' },
    { id: 'brd-3m', name: '3M', logo: 'images/brandlogos/3mlogo.webp', description: 'American multinational conglomerate corporation operating in the fields of industry, worker safety, health care, and consumer goods.' },
    { id: 'brd-medela', name: 'Medela', logo: 'images/brandlogos/medelalogo.webp', description: 'Swiss medical technology company specializing in breastfeeding products and medical vacuum technology.' },
    { id: 'brd-nivea', name: 'Nivea', logo: 'images/brandlogos/nivealogo.webp', description: 'German personal care brand that specializes in skin and body-care products.' },
    { id: 'brd-tefal', name: 'Tefal', logo: 'images/brandlogos/tefallogo.webp', description: 'French cookware and small appliance manufacturer, owned by Groupe SEB (a global manufacturer of small appliances).' },
    { id: 'brd-gopro', name: 'GoPro', logo: 'images/brandlogos/goprolog.webp', description: 'American technology company that manufactures action cameras and develops its own mobile apps and video-editing software.' },
    { id: 'brd-garmin', name: 'Garmin', logo: 'images/brandlogos/garminlogo.webp', description: 'American multinational technology company that develops, manufactures, and markets GPS technology for automotive, aviation, marine, outdoor, and sport activities.' },
    { id: 'brd-mattel', name: 'Mattel', logo: 'images/brandlogos/mattellogo.webp', description: 'American multinational toy manufacturing and entertainment company. The world\'s second-largest toy maker in terms of revenue.' },
    { id: 'brd-lego', name: 'Lego', logo: 'images/brandlogos/legologo.webp', description: 'Danish toy production company best known for manufacturing Lego-brand toys, consisting mostly of interlocking plastic bricks.' },
    { id: 'brd-loreal', name: 'L\'Oreal', logo: 'images/brandlogos/loreallogo.webp', description: 'French personal care company, the largest cosmetics company in the world.' },
    { id: 'brd-garnier', name: 'Garnier', logo: 'images/brandlogos/garnierlogo.webp', description: 'French cosmetics brand of L\'Oréal. It produces hair care and skin care products.' },
    { id: 'brd-stanley', name: 'Stanley', logo: 'images/brandlogos/stanleylogo.webp', description: 'American manufacturer of tools and household hardware, a brand of Stanley Black & Decker.' },
    { id: 'brd-purina', name: 'Purina', logo: 'images/brandlogos/purinalogo.webp', description: 'American company that produces pet food, animal feed, and pet care products. A subsidiary of Nestlé.' }
];

const CATEGORY_DATA = [
    { name: 'Electronics', displayName: 'Electronics', subCategories: ['Smartphones', 'Laptops', 'TVs', 'Audio', 'Wearables', 'Cameras'] },
    { name: 'Fashion & Apparel', displayName: 'Fashion & Apparel', subCategories: ["Men's Clothing", "Women's Clothing", "Kid's Apparel", 'Shoes', 'Accessories'] },
    { name: 'Home & Kitchen', displayName: 'Home & Kitchen', subCategories: ['Appliances', 'Furniture', 'Cookware', 'Decor', 'Bedding'] },
    { name: 'Beauty & Personal Care', displayName: 'Beauty & Personal Care', subCategories: ['Skincare', 'Haircare', 'Makeup', 'Fragrances', 'Grooming'] },
    { name: 'Sports & Outdoors', displayName: 'Sports & Outdoors', subCategories: ['Fitness', 'Camping', 'Cycling', 'Team Sports', 'Outdoor Gear'] },
    { name: 'Books, Movies & Music', displayName: 'Books, Movies & Music', subCategories: ['Books', 'Movies', 'Music', 'Video Games'] },
    { name: 'Toys & Games', displayName: 'Toys & Games', subCategories: ["Kid's Toys", 'Board Games', 'Puzzles', 'Action Figures'] },
    { name: 'Baby & Kids', displayName: 'Baby & Kids', subCategories: ['Baby Gear', 'Diapers', 'Feeding', 'Nursery', 'Kids Furniture'] },
    { name: 'Automotive & Tools', displayName: 'Automotive & Tools', subCategories: ['Car Parts', 'Auto Accessories', 'Hand Tools', 'Power Tools'] },
    { name: 'Health & Wellness', displayName: 'Health & Wellness', subCategories: ['Vitamins', 'Medical Devices', 'Personal Health', 'Fitness Trackers'] },
    { name: 'Pet Supplies', displayName: 'Pet Supplies', subCategories: ['Dog Food', 'Cat Food', 'Pet Toys', 'Grooming', 'Beds'] },
    { name: 'Office & Stationery', displayName: 'Office & Stationery', subCategories: ['Office Furniture', 'Desk Accessories', 'Printers', 'Stationery'] },
    { name: 'Security & Protection', displayName: 'Security & Protection', subCategories: ['Home Security', 'Personal Safety', 'CCTV', 'Alarms'] },
    { name: 'Lingerie & Loungewear', displayName: 'Lingerie & Loungewear', subCategories: ['Lingerie Sets', 'Pajamas', 'Robes', 'Underwear'] },
    { name: 'Special Occasion Costume', displayName: 'Special Occasion Costume', subCategories: ['Halloween', 'Cosplay', 'Party', 'Historical'] }
];
